# Generated by Django 2.2.4 on 2021-04-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nugget_app', '0002_auto_20210401_0007'),
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
