# Generated by Django 2.2 on 2021-02-02 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('login_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('image_upload', models.ImageField(blank=True, null=True, upload_to='uploads/images/')),
            ],
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=255)),
                ('video', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('audio', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Nugget',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='nugget_app.File')),
                ('media_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='nugget_app.MediaType')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nuggets', to='login_app.User')),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='media_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='nugget_app.MediaType'),
        ),
    ]
